# 配置文件版本 / Configuration version
version: 1.1

# 语言（en或zh_cn）
# Language, en / zh_cn
language: zh_cn

# yml或mysql，必选项
# yml or mysql
storage: yml

# 玩家进服后恢复飞行前延时的时间，单位为tick
# The delay time (in ticks) for restoring flight after a player joins the server
tick_delay: 10

# 若存储选项选择mysql则必填下面内容
# database settings
mysql:
  host: localhost
  port: 3306
  database: database_name
  username: database_username
  password: database_password